# field_maps.py

# Example field map for Passport Application
passport_field_map = {
    
  "Your name as printed on your most recent U": "Your name as printed on your most recent U",
  "Your name as printed on your most recent U.S": "Your name as printed on your most recent U.S",
  "Your name as printed on your most recent U.S. passport book and/or passport card": "Your name as printed on your most recent U.S. passport book and/or passport card",
  "Most recent U": "Most recent U",
  "Most recent U.S": "Most recent U.S",
  "Most recent U.S. passport book number": "Most recent U.S. passport book number",
  "Most recent U.S. passport card number": "Most recent U.S. passport card number",
  "Card Issue Date mm/dd/yyyy": "Card Issue Date mm/dd/yyyy",
  "Changed by Court Order": "Changed by Court Order",
  "Height": "Height",
  "Employer or School": "Employer or School",
  "Additional Contact Phone Numbers": "Additional Contact Phone Numbers",
  "Emergency Contact Name": "Emergency Contact Name",
  "Emergency Contact Address": "Emergency Contact Address",
  "Emergency Contact City": "Emergency Contact City",
  "Emergency Contact Zip Code": "Emergency Contact Zip Code",
  "Emergency Contact Phone": "Emergency Contact Phone",
  "Relationship to Applicant": "Relationship to Applicant",
  "Travel Departure Date": "Travel Departure Date",
  "Travel Return Date": "Travel Return Date",
  "Countries to be visited": "Countries to be visited",
  "Changed by Marriage": "Changed by Marriage",
  "16 Years": "16 Years",
  "Less Than 15": "Less Than 15",
  "Damaged": "Damaged",
  "Not Limited": "Not Limited",
  "Name Changed": "Name Changed",
  "Gender": "Gender",
  "Selection": "Selection",
  "Regular or Large Book": "Regular or Large Book",
  "Additional # 1": "Additional # 1",
  "Additional # 2": "Additional # 2",
  "App Name Last": "App Name Last",
  "App First": "App First",
  "App Middle": "App Middle",
  "App Place of Birth": "App Place of Birth",
  "App SSN 1": "App SSN 1",
  "App SSN 2": "App SSN 2",
  "App SSN 3": "App SSN 3",
  "App Email": "App Email",
  "App Phone 1": "App Phone 1",
  "App Phone 2": "App Phone 2",
  "App Phone 3": "App Phone 3",
  "App Mailing Address Country": "App Mailing Address Country",
  "App List all other name you have used": "App List all other name you have used",
  "App List all other names you have used 2": "App List all other names you have used 2",
  "Name Change Date (mm/dd/yyyy)": "Name Change Date (mm/dd/yyyy)",
  "Name Change Place": "Name Change Place",
  "Name of Applicant (Last, First, Middle) 2": "Name of Applicant (Last, First, Middle) 2",
  "Date of Birth 2": "Date of Birth 2",
  "Additional Contact Phone Numbers 2": "Additional Contact Phone Numbers 2",
  "Permanent Address Street": "Permanent Address Street",
  "Permanent Address City": "Permanent Address City",
  "Permanent Address State": "Permanent Address State",
  "Permanent Address Zip Code": "Permanent Address Zip Code",
  "Emerg State": "Emerg State",
  "Emerg Apartment/Unit": "Emerg Apartment/Unit",
  "Perm Apartment/Unit": "Perm Apartment/Unit",
  "Hair Color": "Hair Color",
  "Eye Color": "Eye Color",
  "Occupation": "Occupation",
  "Clear": "Clear",
  "App DOB MM": "App DOB MM",
  "App DOB DD": "App DOB DD",
  "App DOB YYYY": "App DOB YYYY",
  "App Mailing Address Line 1": "App Mailing Address Line 1",
  "App Mailing Address Line 2": "App Mailing Address Line 2",
  "App Mailing Address City": "App Mailing Address City",
  "App Mailing Address State": "App Mailing Address State",
  "App Mailing Address Zip Code": "App Mailing Address Zip Code",
  "Book Issue Date mm/dd/yyyy": "Book Issue Date mm/dd/yyyy",
  "Permanent Address Country": "Permanent Address Country",
  "Emergency Contact Country": "Emergency Contact Country",
  "Emergency Contact Email": "Emergency Contact Email",
  "Most Recent": "Most Recent",
  "Additional#1": "Additional # 1",
  "Additional#2": "Additional # 2",


}

# Example field map for Driver License
Ny_driver_license_field_map = {
    "FULL LAST NAME": "FULL LAST NAME",
    "FULL FIRST NAME": "FULL FIRST NAME",
    "FULL MIDDLE NAME": "FULL MIDDLE NAME",
    "Date of Expiration": "Date of Expiration",
    "Type of License": "Type of License",
    "SUFFIX": "SUFFIX",
    "Feet": "Feet",
    "Inches": "Inches",
    "EYE COLOR": "EYE COLOR",
    "SOCIAL SECURITY NUMBER SSN": "SOCIAL SECURITY NUMBER SSN",
    "Relationship to Applicant": "Relationship to Applicant",
    "PLEASE PRINT NAME": "PLEASE PRINT NAME",
    "APPLYING FOR": "APPLYING FOR",
    "PURPOSE FOR APPLICATION": "PURPOSE FOR APPLICATION",
    "Do you now have or did you ever have a New York driver license learner permit or non driver ID identification card": "Do you now have or did you ever have a New York driver license learner permit or non driver ID identification card",
    "ID Identification NUMBER ON NEW YORK STATE DRIVER LICENSE LEARNER PERMIT or NONDRIVER ID Identification CARD": "ID Identification NUMBER ON NEW YORK STATE DRIVER LICENSE LEARNER PERMIT or NONDRIVER ID Identification CARD",
    "Out of State License ID Identification No Number": "Out of State License ID Identification No Number",
    "SEX": "SEX",
    "TELEPHONE NUMBER Home Mobile": "TELEPHONE NUMBER Home Mobile",
    "TELEPHONE NUMBER Home Mobile Area Code": "TELEPHONE NUMBER Home Mobile Area Code",
    "Has your name changed": "Has your name changed",
    "If you have never been issued a Social Security Number": "If you have never been issued a Social Security Number",
    "ADDRESS WHERE YOU LIVE REQUIRED IF DIFFERENT FROM ADDRESS FOR MAIL DO NOT GIVE PO Post OfficeBOX THIS ADDRESS WILL APPEAR ON YOUR ENHANCED REAL ID IDENTITY DOCUMENT": "ADDRESS WHERE YOU LIVE REQUIRED IF DIFFERENT FROM ADDRESS FOR MAIL DO NOT GIVE PO Post OfficeBOX THIS ADDRESS WILL APPEAR ON YOUR ENHANCED REAL ID IDENTITY DOCUMENT",
    "ADDRESS WHERE YOU LIVE Apt Apartment No Number": "ADDRESS WHERE YOU LIVE Apt Apartment No Number",
    "ADDRESS WHERE YOU LIVE City or Town": "ADDRESS WHERE YOU LIVE City or Town",
    "ADDRESS WHERE YOU LIVE Zip Code": "ADDRESS WHERE YOU LIVE Zip Code",
    "HAS YOUR MAILING ADDRESS CHANGED": "HAS YOUR MAILING ADDRESS CHANGED",
    "HAS THE ADDRESS WHERE YOU LIVE CHANGED": "HAS THE ADDRESS WHERE YOU LIVE CHANGED",
    "If you answered yes to either of the questions above then addresses on all vehicle registrations tied to your ID Identification number will also be updated with this address unless you check this box": "If you answered yes to either of the questions above then addresses on all vehicle registrations tied to your ID Identification number will also be updated with this address unless you check this box",
    "If you do NOT want your new address on your voter registration record check this box": "If you do NOT want your new address on your voter registration record check this box",
    "Check this box to make a 1 voluntary donation to the Life Pass It On Trust Fund for organ and tissue donation research and outreach Your total transaction fee will include the 1": "Check this box to make a 1 voluntary donation to the Life Pass It On Trust Fund for organ and tissue donation research and outreach Your total transaction fee will include the 1",
    "If you are not registered to vote where you live now would you like to apply to register": "If you are not registered to vote where you live now would you like to apply to register",
    "Should you elect not to register you may do so by checking the No box and the pre mentioned benefits will be lost NO": "Should you elect not to register you may do so by checking the No box and the pre mentioned benefits will be lost NO",
    "Has your driver license learner permit or privilege to drive a motor vehicle been suspended revoked or cancelled or has your application for a license been denied in this state or elsewhere in the name you provide on this form or any other name": "Has your driver license learner permit or privilege to drive a motor vehicle been suspended revoked or cancelled or has your application for a license been denied in this state or elsewhere in the name you provide on this form or any other name",
    "Do you need a hearing aid and or full view mirror to drive a motor vehicle": "Do you need a hearing aid and or full view mirror to drive a motor vehicle",
    "Have you lost the use of a leg arm hand or eye": "Have you lost the use of a leg arm hand or eye",
    "If you need to renew your driver license and you marked Yes did this occur since your last driver license": "If you need to renew your driver license and you marked Yes did this occur since your last driver license",
    "If you marked NO to 4a has your condition gotten worse since your last driver license": "If you marked NO to 4a has your condition gotten worse since your last driver license",
    "License Type": "License Type",
    "ID Identification Number on New York State Driver License Permit or Non Driver ID Identification Card of Consenting Parent or Guardian Above Required": "ID Identification Number on New York State Driver License Permit or Non Driver ID Identification Card of Consenting Parent or Guardian Above Required",
    "In the past 10 years was a driver license issued to you from another state in the US or the District of Columbia": "In the past 10 years was a driver license issued to you from another state in the US or the District of Columbia",
    "Are you subject to any disqualification under section 383 51 title 49 of Code of Federal Regulations or NYS New York State Law": "Are you subject to any disqualification under section 383 51 title 49 of Code of Federal Regulations or NYS New York State Law",
    "You MUST certify to DMV Department of Motor Vehicles that you operate or expect to operate a commercial motor vehicle in one of the following four driving types": "You MUST certify to DMV Department of Motor Vehicles that you operate or expect to operate a commercial motor vehicle in one of the following four driving types",
    "Date": "Date",
    "Are you a citizen of the US": "Are you a citizen of the US",
    "Have you voted before": "Have you voted before",
    "What Year": "What Year",
    "Will you be 18 years of age or older on or before election day": "Will you be 18 years of age or older on or before election day",
    "Are you at least 16 years of age and understand that you must be 18 years of age on or before election day to vote and that until you will be eighteen years of age at the time or such election your registration will be marked pending and you will be unable to cast a ballot in any such election": "Are you at least 16 years of age and understand that you must be 18 years of age on or before election day to vote and that until you will be eighteen years of age at the time or such election your registration will be marked pending and you will be unable to cast a ballot in any such election",
    "Your name was": "Your name was",
    "Your address was": "Your address was",
    "Email": "Email",
    "Your state or New York State County was": "Your state or New York State County was",
    "Telephone Number": "Telephone Number",
    "Other specify": "Other specify",
    "I wish to enroll in a political party": "I wish to enroll in a political party",
    "AFFIDAVIT Date": "AFFIDAVIT Date",
    "OTHER CHANGE What is the change and the reason for it new license class wrong date of birth etc Et cetera": "OTHER CHANGE What is the change and the reason for it new license class wrong date of birth etc Et cetera",
    "Check this box if you would like to have Veteran printed on the front of your photo document You must present proof that indicates an honorable discharge from military service ex Example DD214 DD215": "Check this box if you would like to have Veteran printed on the front of your photo document You must present proof that indicates an honorable discharge from military service ex Example DD214 DD215",
    "reset clear": "reset clear",
    "ADDRESS WHERE YOU GET YOUR MAIL Include Street Number and Name Rural Delivery and or box number If PO Post Office Box also fill in Address Where You Live below": "ADDRESS WHERE YOU GET YOUR MAIL Include Street Number and Name Rural Delivery and or box number If PO Post Office Box also fill in Address Where You Live below",
    "ADDRESS WHERE YOU GET YOUR MAIL Apt Apartment No Number": "ADDRESS WHERE YOU GET YOUR MAIL Apt Apartment No Number",
    "ADDRESS WHERE YOU GET YOUR MAIL City or Town": "ADDRESS WHERE YOU GET YOUR MAIL City or Town",
    "ADDRESS WHERE YOU GET YOUR MAIL State": "ADDRESS WHERE YOU GET YOUR MAIL State",
    "ADDRESS WHERE YOU GET YOUR MAIL Zip Code": "ADDRESS WHERE YOU GET YOUR MAIL Zip Code",
    "ADDRESS WHERE YOU GET YOUR MAIL County": "ADDRESS WHERE YOU GET YOUR MAIL County",
    "ADDRESS WHERE YOU LIVE State": "ADDRESS WHERE YOU LIVE State",
    "Have you received treatment do you currently receive treatment or do you take medication for any condition that causes unconsciousness or unawareness for example a convulsive disorder epilepsy fainting or dizziness or a heart condition": "Have you received treatment do you currently receive treatment or do you take medication for any condition that causes unconsciousness or unawareness for example a convulsive disorder epilepsy fainting or dizziness or a heart condition",
    "Would you like to be added to the Donate Life Registry": "Would you like to be added to the Donate Life Registry",
    "DATE OF BIRTH Month": "DATE OF BIRTH Month",
    "DATE OF BIRTH Day": "DATE OF BIRTH Day",
    "DATE OF BIRTH Year": "DATE OF BIRTH Year",
    "ADDRESS WHERE YOU LIVE County": "ADDRESS WHERE YOU LIVE County",
    "Donor Consent Date": "Donor Consent Date",
    "CERTIFICATION DATE Month": "CERTIFICATION DATE Month",
    "CERTIFICATION DATE Day": "CERTIFICATION DATE Day",
    "CERTIFICATION DATE Year": "CERTIFICATION DATE Year",
    "Has your name changed If Yes print your former name exactly as it appears on your present license or nondriver ID Identification card": "Has your name changed If Yes print your former name exactly as it appears on your present license or nondriver ID Identification card",
    "Has your driver license learner permit or privilege to drive a motor vehicle been suspended revoked or cancelled or has your application for a license been denied in this state or elsewhere in the name you provide on this form or any other name If Yes has your license permit or privilege been restored or has your application been approved": "Has your driver license learner permit or privilege to drive a motor vehicle been suspended revoked or cancelled or has your application for a license been denied in this state or elsewhere in the name you provide on this form or any other name If Yes has your license permit or privilege been restored or has your application been approved",
    "In the past 10 years was a driver license issued to you from another state in the US or the District of Columbia If YES write the name of each one": "In the past 10 years was a driver license issued to you from another state in the US or the District of Columbia If YES write the name of each one",
    "Do you have a permit or driver license that is valid or that has expired within the last two years issued by any place other than New York State If Yes where was it issued": "Do you have a permit or driver license that is valid or that has expired within the last two years issued by any place other than New York State If Yes where was it issued",
    "Do you have a permit or driver license that is valid or that has expired within the last two years issued by any place other than New York State": "Do you have a permit or driver license that is valid or that has expired within the last two years issued by any place other than New York State"
}



# Example field map for Social Security Card
passport_apply_field_map = {
    "Selection_1": "Selection_1",
    "Selection_2": "Selection_2",
    "Selection_3": "Selection_3",
    "Regular_or_Large_Book_1": "Regular_or_Large_Book_1",
    "Regular_or_Large_Book_2": "Regular_or_Large_Book_2",
    "Applicant_Last_Name": "Applicant_Last_Name",
    "Applicant_First_Name": "Applicant_First_Name",
    "Applicant_Middle_Name": "Applicant_Middle_Name",
    "Applicant_DOB_M": "Applicant_DOB_M",
    "Applicant_DOB_D": "Applicant_DOB_D",
    "Applicant_DOB_Y": "Applicant_DOB_Y",
    "Gender_1": "Gender_1",
    "Gender_2": "Gender_2",
    "Applicant_Place_of_Birth": "Applicant_Place_of_Birth",
    "Applicant_SSN_1": "Applicant_SSN_1",
    "Applicant_SSN_2": "Applicant_SSN_2",
    "Applicant_SSN_3": "Applicant_SSN_3",
    "Alien_Number": "Alien_Number",
    "Applicant_Email": "Applicant_Email",
    "Applicant_Address_Street": "Applicant_Address_Street",
    "Address_Line_2": "Address_Line_2",
    "Applicant_Address_City": "Applicant_Address_City",
    "Applicant_Address_State": "Applicant_Address_State",
    "Applicant_Address_Zip_Code": "Applicant_Address_Zip_Code",
    "Applicant_Address_Country": "Applicant_Address_Country",
    "Applicant_Phone_1": "Applicant_Phone_1",
    "Applicant_Phone_2": "Applicant_Phone_2",
    "Applicant_Phone_3": "Applicant_Phone_3",
    "List_all_other_name_you_have_used_1": "List_all_other_name_you_have_used_1",
    "List_all_other_names_you_have_used_2": "List_all_other_names_you_have_used_2",
    "Name_of_Applicant_2": "Name_of_Applicant_2",
    "Applicant_DOB_2": "Applicant_DOB_2",
    "Parent_1_FM_Name": "Parent_1_FM_Name",
    "Parent_1_Last_Name": "Parent_1_Last_Name",
    "Parent_1_DOB": "Parent_1_DOB",
    "Parent_1_Place_of_Birth": "Parent_1_Place_of_Birth",
    "Parent_1_Gender_1": "Parent_1_Gender_1",
    "Parent_1_Gender_2": "Parent_1_Gender_2",
    "Parent_1_US_Citizen_1": "Parent_1_US_Citizen_1",
    "Parent_1_US_Citizen_2": "Parent_1_US_Citizen_2",
    "Parent_2_FM_Name": "Parent_2_FM_Name",
    "Parent_2_Last_Name": "Parent_2_Last_Name",
    "Parent_2_DOB": "Parent_2_DOB",
    "Parent_2_Place_of_Birth": "Parent_2_Place_of_Birth",
    "Parent_2_Gender_1": "Parent_2_Gender_1",
    "Parent_2_Gender_2": "Parent_2_Gender_2",
    "Parent_2_US_Citizen_1": "Parent_2_US_Citizen_1",
    "Parent_2_US_Citizen_2": "Parent_2_US_Citizen_2",
    "Ever_Married_1": "Ever_Married_1",
    "Ever_Married_2": "Ever_Married_2",
    "Full_Name_of_Current_Spouse": "Full_Name_of_Current_Spouse",
    "Current_Spouse_DOB": "Current_Spouse_DOB",
    "Current_Spouse_Place_of_Birth": "Current_Spouse_Place_of_Birth",
    "Spouse_US_Citizen_1": "Spouse_US_Citizen_1",
    "Spouse_US_Citizen_2": "Spouse_US_Citizen_2",
    "Date_of_Marriage": "Date_of_Marriage",
    "Divorced_1": "Divorced_1",
    "Divorced_2": "Divorced_2",
    "Widow_Divorce_Date": "Widow_Divorce_Date",
    "Applicant_Additional_Contact_Phone_Numbers": "Applicant_Additional_Contact_Phone_Numbers",
    "Additional_1": "Additional_1",
    "Additional_2": "Additional_2",
    "Additional_3": "Additional_3",
    "Additional_4": "Additional_4",
    "Occupation": "Occupation",
    "Employer_or_School": "Employer_or_School",
    "Height": "Height",
    "Hair_Color": "Hair_Color",
    "Eye_Color": "Eye_Color",
    "Travel_Departure_Date": "Travel_Departure_Date",
    "Travel_Return_Date": "Travel_Return_Date",
    "Countries_to_be_visited": "Countries_to_be_visited",
    "Permanent_Address_Street": "Permanent_Address_Street",
    "Permanent_Address_Apartment_Unit": "Permanent_Address_Apartment_Unit",
    "Permanent_Address_City": "Permanent_Address_City",
    "Permanent_Address_State": "Permanent_Address_State",
    "Permanent_Address_Zip_Code": "Permanent_Address_Zip_Code",
    "Emergency_Contact_Name": "Emergency_Contact_Name",
    "Emergency_Contact_Address": "Emergency_Contact_Address",
    "Emergency_Contact_Apartment_Unit": "Emergency_Contact_Apartment_Unit",
    "Emergency_Contact_City": "Emergency_Contact_City",
    "Emergency_Contact_State": "Emergency_Contact_State",
    "Emergency_Contact_Zip_Code": "Emergency_Contact_Zip_Code",
    "Emergency_Contact_Phone": "Emergency_Contact_Phone",
    "Relationship_to_Applicant": "Relationship_to_Applicant",
    "Ever_Applied_or_Issued_1": "Ever_Applied_or_Issued_1",
    "Ever_Applied_or_Issued_2": "Ever_Applied_or_Issued_2",
    "Your_name_as_printed_on_your_most_recent_passport_book_and_or_card": "Your_name_as_printed_on_your_most_recent_passport_book_and_or_card",
    "Book_Status_Submitting": "Book_Status_Submitting",
    "Book_Status_Stolen": "Book_Status_Stolen",
    "Book_Status_Lost": "Book_Status_Lost",
    "Book_Status_Possession": "Book_Status_Possession",
    "Card_Status_Submitting": "Card_Status_Submitting",
    "Card_Status_Stolen": "Card_Status_Stolen",
    "Card_Status_Lost": "Card_Status_Lost",
    "Card_Status_Possession": "Card_Status_Possession",
    "Name_as_printed_on_your_most_recent_passport_card": "Name_as_printed_on_your_most_recent_passport_card",
    "Circumstances_of_lost_stolen_book_card": "Circumstances_of_lost_stolen_book_card",
    "Clear": "Clear"
}



# Master dictionary to select based on filename
FIELD_MAPS = {
    "passport": passport_field_map,
    "driver_license": Ny_driver_license_field_map,
    "passport_apply": passport_apply_field_map,
}
